# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-Q2iATEIwCHrBvEZTdbfY4kfcfIbsJm
"""

!pip install google-generativeai

import google.generativeai as genai

from google.colab import userdata

genkey = userdata.get("GEMINI_API_KEY")

genai.configure(api_key=genkey)

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel("gemini-1.5-flash")

chat = model.start_chat(history=[])

prompt = input("Digite sua primeira mensagem para começar a interagir com a IA.")

while prompt != "fim":
  response = chat.send_message(prompt)
  print(response.text)
  prompt = input("Digite sua mensagem:")

